package dag

import (
	"errors"
	"fmt"
)

// This file is the map fan-out contract half of ADR-015 (ticket 13.4): the
// validation of the definition's `templates` library and of `map` steps that
// reference it. A template is a self-contained sub-graph the engine
// instantiates once per runtime list item (mapexpand.go generates the delta);
// it is validated like a mini definition — its own id space, its edges local,
// acyclic, and with exactly one sink step whose output the generated gather
// join collects.

// checkTemplateSection validates every sub-template in the definition's
// `templates` library (ADR-015): each is a well-formed sub-graph with unique
// local ids, valid per-step config, local-only edges, no cycles, at least one
// entry and exactly one sink, and template references (`${{ item }}`,
// `${{ item_index }}`, `${{ steps.<local>.output }}`, `${{ run.params.<key> }}`)
// that resolve within the template. A template is a library entry, not an
// active step, so its validation is self-contained and independent of the main
// graph — an unreferenced but malformed template is still an error.
func (v *validator) checkTemplateSection(def *Definition) {
	for _, name := range sortedKeys(def.Templates) {
		t := def.Templates[name]
		base := "templates." + name
		if !stepIDRe.MatchString(name) {
			v.add(CodeTemplateSectionInvalid, base, "template name %q does not match %s", name, stepIDRe)
		}
		if t == nil || len(t.Steps) == 0 {
			v.add(CodeTemplateSectionInvalid, base+".steps", "a map sub-template must have at least one step")
			continue
		}

		index := make(map[string]int, len(t.Steps))
		wellFormed := true
		for i, s := range t.Steps {
			sp := fmt.Sprintf("%s.steps[%d]", base, i)
			if !stepIDRe.MatchString(s.ID) {
				v.add(CodeInvalidStepID, sp+".id", "step ID %q does not match %s", s.ID, stepIDRe)
			}
			if first, dup := index[s.ID]; dup {
				v.add(CodeDuplicateStepID, sp+".id", "duplicate step ID %q (first at steps[%d])", s.ID, first)
				wellFormed = false
			} else {
				index[s.ID] = i
			}
			_, registered := stepConfigTypes[s.Type]
			switch {
			case !registered:
				v.add(CodeUnknownStepType, sp+".type", "unknown step type %q", string(s.Type))
			case s.Type == StepMap:
				// Nesting a map inside a map body is deferred (ADR-015): a body
				// instance would expand again, and 13.4 does not compose the two.
				v.add(CodeTemplateSectionInvalid, sp+".type", "a map sub-template body may not itself contain a map step")
			case s.Type == StepGather:
				// The gather is generated by the map expansion; authoring one
				// inside a body is a mistake (the body has its own generated one).
				v.add(CodeTemplateSectionInvalid, sp+".type", "a map sub-template body may not contain a gather step")
			}
			v.checkStepConfig(sp, s)
			v.checkModelFallbacks(def, sp, s)
			v.checkOutputFormat(sp, s)
			v.checkRetry(sp, s.Retry)
			v.checkTimeout(sp, s.Timeout)
			v.checkCache(sp, s.Cache)
			v.checkStepBudget(sp, s.Type, s.Budget)
			v.checkValidation(sp, s)
			v.checkBlackboard(sp, s.Blackboard)
			v.checkContext(sp, s)
		}

		for i, e := range t.Edges {
			ep := fmt.Sprintf("%s.edges[%d]", base, i)
			if _, ok := index[e.From]; !ok {
				v.add(CodeUnknownEdgeEndpoint, ep+".from", "edge names unknown step %q (not in this template)", e.From)
				wellFormed = false
			}
			if _, ok := index[e.To]; !ok {
				v.add(CodeUnknownEdgeEndpoint, ep+".to", "edge names unknown step %q (not in this template)", e.To)
				wellFormed = false
			}
			v.checkExpansionEdgeFields(ep, e)
		}

		if wellFormed {
			// A sub-definition sharing the template's steps/edges: NewGraph
			// succeeds now that ids are unique and endpoints resolve, so the
			// acyclicity / sink / reference checks reuse the graph algorithms.
			sub := &Definition{Steps: t.Steps, Edges: t.Edges}
			if g, err := NewGraph(sub); err == nil {
				v.checkTemplateGraph(def, base, sub, g)
			}
		}
	}
}

// checkTemplateGraph enforces the sub-graph shape a map body must have: no
// normal-edge cycles (marked loop edges keep their ancestry rule), and exactly
// one sink step — the terminal whose output the generated gather join collects.
// A body with several sinks would leave the gather's result ambiguous, and one
// with none could never terminate. It then lints the body's template
// references against the sub-graph.
func (v *validator) checkTemplateGraph(def *Definition, base string, sub *Definition, g *Graph) {
	for _, c := range g.findCycles() {
		v.add(CodeCycle, fmt.Sprintf("%s.edges[%d]", base, c.edgeIdx),
			"edge closes the cycle %s (mark a loop edge instead: only loop edges may form cycles)", c.pathString())
	}
	for _, ei := range g.loopEdges {
		e := sub.Edges[ei]
		if !g.reaches(g.index[e.To], g.index[e.From]) {
			v.add(CodeLoopEdgeNotAncestor, fmt.Sprintf("%s.edges[%d]", base, ei),
				"loop edge target %q is not an ancestor of source %q (no loop body to iterate)", e.To, e.From)
		}
	}
	var sinks []string
	for i, s := range sub.Steps {
		if len(g.outNormal[i]) == 0 {
			sinks = append(sinks, s.ID)
		}
	}
	if len(sinks) != 1 {
		v.add(CodeTemplateSectionInvalid, base,
			"a map sub-template must have exactly one sink (a step with no outgoing normal edge, whose output the gather collects); found %d %v", len(sinks), sinks)
	}
	v.checkTemplateRefs(def, base, sub, g)
}

// checkTemplateRefs lints the `${{ ... }}` references inside a map body's step
// configs: `item` / `item_index` are the sanctioned per-item roots; a
// `steps.<id>` reference must name a template-local step that is strictly
// upstream via normal edges; a `run.params.<key>` reference must name a
// declared run parameter. It mirrors checkTemplates so an authored template is
// held to the same reference contract as an authored top-level step.
func (v *validator) checkTemplateRefs(def *Definition, base string, sub *Definition, g *Graph) {
	for i, s := range sub.Steps {
		if s.Config == nil {
			continue
		}
		raw, err := marshalNoEscape(s.Config)
		if err != nil || !HasTemplate(string(raw)) {
			continue
		}
		stepBase := fmt.Sprintf("%s.steps[%d].config", base, i)
		ct, perr := ParseConfigTemplates(raw)
		if perr != nil {
			for _, subErr := range flatten(perr) {
				var re *TemplateRefError
				var te *TemplateError
				switch {
				case errors.As(subErr, &re):
					v.add(CodeTemplateRefInvalid, tmplIssuePath(stepBase, re.Path), "invalid reference %q: %s", re.Ref, re.Msg)
				case errors.As(subErr, &te):
					v.add(CodeTemplateInvalid, tmplIssuePath(stepBase, te.Path), "%s", te.Msg)
				default:
					v.add(CodeTemplateInvalid, stepBase, "%v", subErr)
				}
			}
			continue
		}
		var ancestors map[string]bool // lazy: one BFS per referencing step
		for _, r := range ct.Refs() {
			if r.Lenient || r.ItemRef {
				continue // item roots are always valid inside a body
			}
			path := tmplIssuePath(stepBase, r.ConfigPath)
			switch {
			case r.StepID != "":
				if ancestors == nil {
					ancestors, _ = g.Ancestors(s.ID)
				}
				switch classifyUpstreamRef(g, s.ID, r.StepID, ancestors) {
				case refUnknownStep:
					v.add(CodeTemplateRefUnknownStep, path, "reference %q names unknown step %q (a map body may only reference its own steps)", r.Raw, r.StepID)
				case refSelf:
					v.add(CodeTemplateRefNotUpstream, path, "reference %q: a step cannot reference its own output", r.Raw)
				case refNotAncestor:
					v.add(CodeTemplateRefNotUpstream, path, "reference %q: step %q is not upstream of %q (no normal-edge path)", r.Raw, r.StepID, s.ID)
				case refOK:
				}
			case r.ParamKey != "":
				if _, declared := def.Params[r.ParamKey]; !declared {
					v.add(CodeTemplateRefUnknownParam, path, "reference %q names undeclared run parameter %q", r.Raw, r.ParamKey)
				}
			}
		}
	}
}

// checkMaps validates each `map` step's body reference (ADR-015): `body` must
// name a template declared in the definition's `templates` library. The
// per-item cap and the items grammar are config-level checks (checkStepConfig);
// the template's own well-formedness is checkTemplateSection's.
func (v *validator) checkMaps(def *Definition) {
	for i, s := range def.Steps {
		if s.Type != StepMap {
			continue
		}
		c, ok := s.Config.(*MapConfig)
		if !ok || c == nil || c.Body == "" {
			continue // a missing body was already reported by checkStepConfig
		}
		if _, declared := def.Templates[c.Body]; !declared {
			v.add(CodeMapBodyUnknown, fmt.Sprintf("steps[%d].config.body", i),
				"map body %q names no template in the definition's templates section", c.Body)
		}
	}
}
