// Package store owns agentloom's Postgres persistence layer: schema
// migrations (embedded, applied via golang-migrate), sqlc-generated queries
// (internal/store/gen, regenerated by `make generate`), typed repositories
// over them, and the WithTx transaction helper.
//
// The sqlc-generated row and params types are the store's domain types —
// there is deliberately no hand-written mapping layer on top of them.
// Status/counter mutations are absent from the repository surface on
// purpose: every state transition is a guarded CAS in transitions.go
// (ticket 2.6), the only path that appends the transition's event.
package store

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/mathcslearner/agentloom/internal/store/gen"
)

// Querier bundles the repositories. It is implemented by *Store (executing
// on the pool) and by the handle WithTx passes its callback (executing on
// that transaction), so the same repository code serves both paths.
type Querier interface {
	Definitions() DefinitionRepo
	Runs() RunRepo
	Steps() StepRepo
	Attempts() AttemptRepo
	DeadLetters() DeadLetterRepo
	SideEffects() SideEffectRepo
	StepLogs() StepLogRepo
	Events() EventRepo
	Outbox() OutboxRepo
	APIKeys() APIKeyRepo
	RetrievalDocs() RetrievalDocRepo
	Ledger() CostRepo
	Blackboard() BlackboardRepo
	Approvals() ApprovalRepo
}

// Store is the pool-backed entry point to the persistence layer.
type Store struct {
	repos
	pool *pgxpool.Pool
}

// Open connects a pool to the given DSN and verifies the connection with a
// ping. The caller owns the returned Store and must Close it.
func Open(ctx context.Context, dsn string) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		// Never echo the DSN or the parse error: both can embed credentials.
		return nil, errors.New("store: invalid Postgres DSN")
	}
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("store: opening pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: pinging Postgres: %w", err)
	}
	return NewFromPool(pool), nil
}

// NewFromPool wraps an existing pool (the integration-test harness hands
// these out). The caller keeps ownership of the pool's lifecycle.
func NewFromPool(pool *pgxpool.Pool) *Store {
	return &Store{repos: repos{q: gen.New(pool)}, pool: pool}
}

// Close releases the connection pool.
func (s *Store) Close() {
	s.pool.Close()
}

// Ping verifies database connectivity — the API server's health probe.
func (s *Store) Ping(ctx context.Context) error {
	return s.pool.Ping(ctx)
}

// repos implements Querier over a gen.Queries, which itself runs on either
// the pool or a transaction (gen.Queries.WithTx).
type repos struct {
	q *gen.Queries
}

var _ Querier = repos{}

func (r repos) Definitions() DefinitionRepo { return definitionRepo(r) }
func (r repos) Runs() RunRepo               { return runRepo(r) }
func (r repos) Steps() StepRepo             { return stepRepo(r) }
func (r repos) Attempts() AttemptRepo       { return attemptRepo(r) }
func (r repos) DeadLetters() DeadLetterRepo { return deadLetterRepo(r) }
func (r repos) SideEffects() SideEffectRepo { return sideEffectRepo(r) }
func (r repos) StepLogs() StepLogRepo       { return stepLogRepo(r) }
func (r repos) Events() EventRepo           { return eventRepo(r) }
func (r repos) Outbox() OutboxRepo          { return outboxRepo(r) }
func (r repos) APIKeys() APIKeyRepo         { return apiKeyRepo(r) }

func (r repos) RetrievalDocs() RetrievalDocRepo { return retrievalDocRepo(r) }
func (r repos) Ledger() CostRepo                { return costRepo(r) }
func (r repos) Blackboard() BlackboardRepo      { return blackboardRepo(r) }
func (r repos) Approvals() ApprovalRepo         { return approvalRepo(r) }
